# Generated by Django 3.2 on 2023-08-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230830_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qqq', to='reviews.category', verbose_name='Категория'),
        ),
    ]
